### ISSUE TITLE
Request a sample button not in line with other two buttons

### ISSUE THREAD

**Issue by breenyoung** [breenyoung/fsh#16]
The request sample button seems to sit slightly lower the the other two buttons to its left.

Tested in Chrome 47, IE 11 and FF 43

See attached.

![capture](https://cloud.githubusercontent.com/assets/1478603/12368350/02223ab0-bbc1-11e5-8373-8f86e9b09b9c.PNG)

**Comment by gabwhite** [comment]
should be fixed in all places were two diff colour buttons are next to each other now
