### ISSUE TITLE
<A> links with the button class don't align with items of type <button> on Product Detail

### ISSUE THREAD

**Issue by breenyoung** [breenyoung/fsh#42]
I think this was resolved somewhere else if I remember.

![capture](https://cloud.githubusercontent.com/assets/1478603/12651155/d077e262-c5bb-11e5-830e-fd51b21453fa.PNG)

**Comment by breenyoung** [comment]
Hey @gabwhite was this one resolved in another fix?
Thanks!

**Comment by gabwhite** [comment]
Just took another look at it and pushed up a fix. Should be fixed site-wide now!
